spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: pedido
          uri: lb://PEDIDO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/pedido/**
        - id: cerveja
          uri: lb://CERVEJA-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/cerveja/**

eureka:
  client:
    service-url:
      defaultUrl: http://localhost:8761/eureka
server:
  port: 9098
